name: chatapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.11
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/meetme.png"
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
assets:
  - asset/