// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4yJ1pGDAHlvukaOqXzqP5qsd2DW4u0A0',
    appId: '1:944093326294:web:ceacc8387e6f853fc4d277',
    messagingSenderId: '944093326294',
    projectId: 'chat-app-8ecbc',
    authDomain: 'chat-app-8ecbc.firebaseapp.com',
    storageBucket: 'chat-app-8ecbc.appspot.com',
    measurementId: 'G-NTHLFZ7KKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjIezkKSfUthpIMT-dwcALGC8ec8w2S0A',
    appId: '1:944093326294:android:d01962ec7525afe7c4d277',
    messagingSenderId: '944093326294',
    projectId: 'chat-app-8ecbc',
    storageBucket: 'chat-app-8ecbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaniis5FkUf5IDZ_ZCXFFOLjlJ9nRoHMY',
    appId: '1:944093326294:ios:34829573b0b1103cc4d277',
    messagingSenderId: '944093326294',
    projectId: 'chat-app-8ecbc',
    storageBucket: 'chat-app-8ecbc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaniis5FkUf5IDZ_ZCXFFOLjlJ9nRoHMY',
    appId: '1:944093326294:ios:34829573b0b1103cc4d277',
    messagingSenderId: '944093326294',
    projectId: 'chat-app-8ecbc',
    storageBucket: 'chat-app-8ecbc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4yJ1pGDAHlvukaOqXzqP5qsd2DW4u0A0',
    appId: '1:944093326294:web:01bc3d8479c95d19c4d277',
    messagingSenderId: '944093326294',
    projectId: 'chat-app-8ecbc',
    authDomain: 'chat-app-8ecbc.firebaseapp.com',
    storageBucket: 'chat-app-8ecbc.appspot.com',
    measurementId: 'G-ZF09FCQ2BB',
  );
}
